name: 'docs.ggxchain.io documentation'

on:
  push:
    branches:
      - main
      - honkit-migration # for test purposes
    paths-ignore:
      - '_book/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      # - name: Deploy to GitHub Pages
      #   if: success()
      #   uses: crazy-max/ghaction-github-pages@v3
      #   with:
      #     target_branch: gh-pages
      #     build_dir: _book
      #     fqdn: docs.ggxchain.io
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
